AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  zenpayroll-lambda-rb

  Sample SAM Template for zenpayroll-lambda-rb

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  CreateApplicationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: zenpayroll-api/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: app/*/payroll/doorkeeper_api
      Environment:
        Variables:
          ENV: !Ref ENV
      Events:
        CreateApplication:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /partners/{partnerId}/applications
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateApplicationApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateApplication function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/applications/"
  CreateApplicationFunction:
    Description: "CreateApplication Lambda Function ARN"
    Value: !GetAtt CreateApplicationFunction.Arn
  CreateApplicationFunctionIamRole:
    Description: "Implicit IAM Role created for CreateApplication function"
    Value: !GetAtt CreateApplicationFunctionRole.Arn
