Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Resources:
  CreateOrganizationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Runtime: ruby2.5
      Handler: source.LambdaFunctions::Handler.process
      Events:
        CreateOrganizationApi:
          Type: Api
          Properties:
            Path: /organizations
            Method: get
